#!/bin/sh

set -e
if test -f /usr/share/doc/yang-tools/examples/ietf-interfaces.yang.gz; then
	gunzip -c < /usr/share/doc/yang-tools/examples/ietf-interfaces.yang.gz > /tmp/ietf-interfaces.yang
else
	cp /usr/share/doc/yang-tools/examples/ietf-interfaces.yang /tmp/ietf-interfaces.yang
fi
yanglint /tmp/ietf-interfaces.yang
