#!/usr/bin/expect -f

source [expr {[info exists ::env(CURRENT_SOURCE_DIR)] ? "$env(CURRENT_SOURCE_DIR)/tests/expect/common.exp" : "common.exp"}]

spawn $yanglint
skip_warnings

# default loaded models
command "list" "List of the loaded models:\r
    i ietf-yang-metadata@2016-08-05\r
    I yang@2022-06-16\r
    i ietf-inet-types@2013-07-15\r
    i ietf-yang-types@2013-07-15\r
    I ietf-yang-schema-mount@2019-01-14\r
    i ietf-yang-structure-ext@2020-06-17" -ex

# add models for ietf-yang-library
command "clear -y"

# check that the new models has been added
command "list" "List of the loaded models:\r
    i ietf-yang-metadata@2016-08-05\r
    I yang@2022-06-16\r
    i ietf-inet-types@2013-07-15\r
    i ietf-yang-types@2013-07-15\r
    I ietf-yang-schema-mount@2019-01-14\r
    i ietf-yang-structure-ext@2020-06-17\r
    I ietf-datastores@2018-02-14\r
    I ietf-yang-library@2019-01-04" -ex

# list --format
# print xml format
set modules {complete yang ietf-yang-schema-mount
    ietf-datastores ietf-yang-library ietf-yang-metadata
    ietf-inet-types ietf-yang-types ietf-yang-structure-ext
}
command "list -f xml" [list_to_regex [wrap_to_xml $modules "name"]]
# print json format
command "list -f json" [list_to_regex [wrap_to_json $modules "name"]]

# remove all the loaded modules
command "clear"
command "list" "List of the loaded models:\r
    i ietf-yang-metadata@2016-08-05\r
    I yang@2022-06-16\r
    i ietf-inet-types@2013-07-15\r
    i ietf-yang-types@2013-07-15\r
    I ietf-yang-schema-mount@2019-01-14\r
    i ietf-yang-structure-ext@2020-06-17" -ex

# error message when using --format without ietf-yang-library
command "list -f xml" "libyang\[0\]: Module \"ietf-yang-library\" is not implemented.\r
YANGLINT\[E\]: Getting context info (ietf-yang-library data) failed.\
If the YANG module is missing or not implemented, use an option to add it internally." -ex

send_exit
